[package]
name = "parliant-audio"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
parliant-core.workspace = true
thiserror.workspace = true
signal-hook.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
pipewire.workspace = true
