[package]
name = "sidecar-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sidecar-core.workspace = true
thiserror.workspace = true
signal-hook.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
pipewire.workspace = true
